name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    - name: Validate policies
      uses: gbaeke/kyverno-action@v1.0.0
      with:
        command: |
           kyverno apply ./policies --resource=./deploy/deployment.yaml